# Generated by Django 4.1.7 on 2023-03-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backtest", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parameter", old_name="prams", new_name="period_buy",
        ),
    ]
