# Generated by Django 4.1.7 on 2023-03-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtest", "0002_rename_prams_parameter_period_buy"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="period_sell",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parameter",
            name="standardDeviation_buy",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parameter",
            name="standardDeviation_sell",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="period_buy",
            field=models.CharField(max_length=100),
        ),
    ]
